version: '3'

services:
  web: # Webサーバーコンテナ
    image: nginx
    ports:
      - '8000:80' 
    volumes:
      - ./src/src/public:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    container_name: laravel-app # コンテナ名
    depends_on:
      - app # appコンテナと連携
  
  app: # アプリケーションコンテナ (PHP/Laravel)
    build: ./docker/web
    volumes:
      - ./src/src:/laravel # 開発ディレクトリを公開ディレクトリにマウント
    depends_on:
      - mysql
      - composer
      - webpack
    environment:
      DB_DATABASE: database
      DB_USERNAME: docker
      DB_PASSWORD: docker
      APP_DEBUG: "true"
      APP_KEY: "base64:KlvfsD03qAsi8eOsmSbME8HK2BiH1iIAAGtnbPU3lkc="

  mysql: # データベースコンテナ
    image: mysql:5.7
    environment: # DB設定
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306' #3306番ポートで接続
    container_name: "db-host" 

  phpmyadmin: #PHPMyAdminコンテナ
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql # mysqlを参照
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-host # mysql container_name参照
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    container_name: "phpmyadmin-laravel"

  composer:
    image: composer
    volumes:
      - ./src/src:/app # 開発ディレクトリを公開ディレクトリにマウント
    command: "composer install"
  
  webpack:
    image: node
    volumes:
      - ./src/src:/var/www/html
    working_dir: /var/www/html
    command: [ "bash", "-c", "yarn install --prod && npm run watch-poll"]
